#!/usr/bin/env bash
# See also [Configure script](http://en.wikipedia.org/wiki/Configure_script)
set -o errexit

# Bootstrap
curl -so .roboconf https://raw.github.com/benjaminoakes/roboconf/master/roboconf
source .roboconf

roboconf-check mysql
roboconf-bundler '~> 1.0.0'
roboconf-rails-activerecord
